In [2]:
import DataLoader 
#Test of dataLoader 
#Load model from hopsworks
import pickle
import hopsworks
from DataLoader import DataLoader

#Load the model
#Test of DataLoader

data_loader = DataLoader("AAPL","1y","1y")
data = data_loader.get_data()
data.head(100)

[*********************100%***********************]  1 of 1 completed
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Device set to use mps:0

,Open,Close,High,Low,positive_score,negative_score,neutral_score
2024-01-03,184.220001,184.250000,185.880005,183.429993,0.0,0.0,0.0
2024-01-04,182.149994,181.910004,183.089996,180.880005,0.0,0.0,0.0
2024-01-05,181.990005,181.179993,182.759995,180.169998,0.0,0.0,0.0
2024-01-08,182.089996,185.559998,185.600006,181.500000,0.0,0.0,0.0
2024-01-09,183.919998,185.139999,185.149994,182.729996,0.0,0.0,0.0
...,...,...,...,...,...,...,...
2024-05-20,189.330002,191.039993,191.919998,189.009995,0.0,0.0,0.0
2024-05-21,191.089996,192.350006,192.729996,190.919998,0.0,0.0,0.0
2024-05-22,192.270004,190.899994,192.820007,190.270004,0.0,0.0,0.0
2024-05-23,190.979996,186.880005,191.000000,186.630005,0.0,0.0,0.0
2024-05-24,188.820007,189.979996,190.580002,188.039993,0.0,0.0,0.0

In [ ]:
#Load the m